development:
   adapter: postgresql
   encoding: utf8
   host: localhost
   database: onemdm_dev
   username: postgres
   password: root

test:
   adapter: postgresql
   encoding: utf8
   host: localhost
   database: onemdm_test
   username: postgres
   password: root

production:
   adapter: postgresql
   encoding: utf8
   host: localhost
   database: onemdm_production
   username: postgres
   password: root
